"""Initial migration.

Revision ID: 81c8ade0545a
Revises: 095d7019b871
Create Date: 2024-07-14 10:20:20.011055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c8ade0545a'
down_revision = '095d7019b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studyresources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyresources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('url', sa.VARCHAR(length=120), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
