"""Initial migration.

Revision ID: d982d04bc72b
Revises: 81c8ade0545a
Create Date: 2024-07-14 10:27:27.059565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd982d04bc72b'
down_revision = '81c8ade0545a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studyresources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyresources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('url', sa.VARCHAR(length=120), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
